### ISSUE TITLE
Fixture Libary Autodownload doesn't work

### ISSUE THREAD

**Issue by scheidleon** [hrueger/AGLight#144]
Currently AGLight trys to automaticaly download from https://open-fixture-library-pr-1357.herokuapp.com/download.aglight. Since this link doesn't return a valid libary no fixtures are loaded.

Manually downloading from the open fixture libary homepage and copying to library/library.json works.
I will try to create a PR when i get my dev enviroment set up.

PS
Schön eine neue Software im DMX-Land zu sehen :) Werde die Software am Wochenende mal an ein paar Lampen testen.

Gruß Leon Scheid

**Comment by hrueger** [comment]
Hi,
I forgot to update the url after my export plugin PR in the ofl repository had been merged.
Build is in progress.

As this is now the first "complete" version, I released it as `v.0.1.0`. You should be able to get it with auto update when the GitHub Action run is done.

Feel free to open issues for problems you encounter or feature requests you might have.
I believe you're the first one to use this software aside from me.
